version: '3'
services:

  demo-backend:
    image: "sfeir/backend:latest"
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      - demo-db
    ports:
      - 8080:8080


  demo-frontend:
    image: "sfeir/frontend:latest"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - "demo-backend"
    ports:
      - "8081:8081"
    links:
      - demo-backend

  demo-db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vue
